version: "3.9"
services:
  app:
    container_name: pokemon_api
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "5000:5000"
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge
